---

- name: 'Restart Motion'
  become: true
  systemd:
    name: motion.service
    state: restarted
  listen:
  - 'Restart Motion'

- name: 'Restart Apache'
  become: true
  service:
    name: apache2.service
    state: restarted
  listen:
  - 'Restart Apache'
