---

- name: "HDMI-CEC script exists in system-sleep directory"
  become: true
  ansible.builtin.copy:
    src: hdmi-cec
    dest: /usr/lib/systemd/system-sleep/hdmi-cec
    owner: root
    group: root
    mode: 0700

