---
- name: "Input Remapper preset"
  ansible.builtin.copy:
    src: Xbox.json
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/input-remapper-2/presets/Microsoft Xbox Series S_X Controller/Xbox.json"
    mode: 0600

- name: "Input Remapper configuration file"
  ansible.builtin.copy:
    src: config.json
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/input-remapper-2/config.json"
    mode: 0600
