---

# Docker-CE
- name: 'Docker Linux signing key'
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker-linux.gpg
    state: present

- name: 'Docker repository'
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    state: present
    update_cache: yes
    filename: docker-ce
    mode: 0600

- name: 'Allow Unattended-upgrade to use Docker Repo'
  become: true
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?"Docker:focal";\s*$'
    line: '        "Docker:focal";'
    insertafter: '^\s*(//\s*)?"\${distro_id}:\${distro_codename}-backports";$'

- name: '`docker-ce` package (latest)'
  become: true
  apt:
    name: docker-ce
    force_apt_get: yes
    update_cache: yes
    state: latest
  when: docker_version is undefined

- name: '`docker-ce` package (specific version)'
  become: true
  apt:
    name: docker-ce={{ docker_version }}
    force_apt_get: yes
    update_cache: yes
    state: present
  when: docker_version is defined

- name: 'Add user to `docker` group'
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  register: docker_user_group

- name: 'Note if logout will be required'
  when: docker_user_group.changed
  set_fact:
    logout_required: true

- name: 'Prevent upgrades to docker-ce'
  become: true
  command: apt-mark hold docker-ce
  register: apt_hold_docker
  changed_when: "'docker-ce was already set on hold' not in apt_hold_docker.stdout"
  when: docker_version_hold
