---

- name: 'Ensure the keyrings directory exists'
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: 0755

- name: 'Download Antigravity''s Linux signing key'
  become: true
  ansible.builtin.get_url:
    url: https://us-central1-apt.pkg.dev/doc/repo-signing-key.gpg
    dest: /etc/apt/keyrings/antigravity.asc
    mode: 0644

- name: "Check for existing Antigravity repository file"
  stat:
    path: /etc/apt/sources.list.d/antigravity.list
  register: antigravity_file

- name: "Backup any existing Antigravity repository file"
  become: true
  copy:
    remote_src: yes
    src: /etc/apt/sources.list.d/antigravity.list
    dest: "{{ backup_dir }}/antigravity.list"
  when: antigravity_file.stat.exists
  changed_when: false

- name: "Antigravity repository"
  become: true
  copy:
    src: antigravity.list
    dest: /etc/apt/sources.list.d/antigravity.list
    mode: 0644

- name: "Apt update cache"
  become: true
  apt:
    update_cache: true
  changed_when: false

# sudo apt-cache policy -> o:a pairs (e.g. antigravity-debian:antigravity-debian)
- name: "Allow Unattended-upgrade to use Antigravity Repo"
  become: true
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?"antigravity-debian:antigravity-debian";\s*$'
    line: '        "antigravity-debian:antigravity-debian";'
    insertafter: '^\s*(//\s*)?"\${distro_id}:\${distro_codename}-backports";$'

- name: "`apt-transport-https` package"
  become: true
  apt:
    name: apt-transport-https
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: "`antigravity` package"
  become: true
  apt:
    name: antigravity
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: "`~/.antigravity/` directory"
  file:
    path: "{{ ansible_env.HOME }}/.antigravity/"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0700

- name: "Check if there is an existing `~/.config/Antigravity/User/settings.json`"
  stat:
    path: "{{ ansible_env.HOME }}/.config/Antigravity/User/settings.json"
  register: antigravity_config
  changed_when: false

- name: "Backup existing `~/.config/Antigravity/User/settings.json`"
  when: antigravity_config.stat.exists
  copy:
    remote_src: yes
    src: "{{ ansible_env.HOME }}/.config/Antigravity/User/settings.json"
    dest: "{{ backup_dir }}/settings.json"
  changed_when: false

- name: "Check if there is an existing `~/.config/Antigravity/User/keybindings.json`"
  stat:
    path: "{{ ansible_env.HOME }}/.config/Antigravity/User/keybindings.json"
  register: antigravity_keybindings
  changed_when: false

- name: "Backup existing `~/.config/Antigravity/User/keybindings.json`"
  when: antigravity_keybindings.stat.exists
  copy:
    remote_src: yes
    src: "{{ ansible_env.HOME }}/.config/Antigravity/User/keybindings.json"
    dest: "{{ backup_dir }}/keybindings.json"
  changed_when: false

- name: "Config file directory structure"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0700
  with_items:
    - ~/.config/
    - ~/.config/Antigravity/
    - ~/.config/Antigravity/User/

- name: "Deploy `~/.config/Antigravity/User/settings.json`"
  copy:
    content: |
      {
        "editor.acceptSuggestionOnEnter": "off",
        "editor.fontFamily": "'Source Code Pro', 'monospace', monospace",
        "editor.tabSize": 2,
        "editor.wordWrap": "bounded",
        "editor.wordWrapColumn": 79,
        "explorer.compactFolders": false,
        "explorer.confirmDragAndDrop": false,
        "telemetry.telemetryLevel": "off",
        "workbench.editor.untitled.hint": "hidden",
        "workbench.panel.defaultLocation": "right",
        "workbench.panel.opensMaximized": "always",
        "workbench.startupEditor": "none"
      }
    dest: "{{ ansible_env.HOME }}/.config/Antigravity/User/settings.json"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "Deploy `~/.config/Antigravity/User/keybindings.json`"
  copy:
    content: |
      // Place your key bindings in this file to override the defaults
      [
        {
          "key": "ctrl+l",
          "command": "workbench.action.terminal.clear",
          "when": "terminalFocus"
        },
        {
          "key": "ctrl+l",
          "command": "-workbench.action.chat.newChat"
        },
        {
          "key": "ctrl+l",
          "command": "-workbench.action.chat.focus"
        },
        {
          "key": "ctrl+l",
          "command": "-workbench.action.chat.open"
        }
      ]
    dest: "{{ ansible_env.HOME }}/.config/Antigravity/User/keybindings.json"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "List Antigravity extensions"
  command: antigravity --list-extensions
  register: antigravity_extensions_installed
  changed_when: false

- name: "Install Antigravity extensions"
  command: antigravity --install-extension {{ item }}
  when: item not in antigravity_extensions_installed.stdout
  loop: "{{ query('items', antigravity.extensions )}}"
