---

# https://wiki.archlinux.org/title/Atom_(text_editor)#Unable_to_delete_files
- name: 'Electron Fix'
  lineinfile:
    create: yes
    line: export ELECTRON_TRASH=gio
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
