---

apt_packages_desktop:
# Desktop Environment customization
- vanilla-gnome-default-settings # universe
- vanilla-gnome-desktop          # universe
- adwaita-icon-theme-full        # universe
# Utilities
- gimp                           # universe
- vlc                            # universe
- gparted                        # main

google_fonts:
- src: 'Source%20Sans%20Pro'
  dest: 'source-sans-pro'
- src: 'Source%20Code%20Pro'
  dest: 'source-code-pro'

dconf_options:
- key: /org/gnome/desktop/background/show-desktop-icons
  value: "false"
- key: /org/gnome/desktop/interface/gtk-theme
  value: "'Adwaita-dark'"
- key: /org/gnome/desktop/interface/icon-theme
  value: "'Adwaita-dark'"
- key: /org/gnome/desktop/interface/cursor-theme
  value: "'Adwaita-dark'"
- key: /org/gnome/desktop/interface/clock-show-date
  value: "true"
- key: /org/gnome/desktop/interface/clock-show-seconds
  value: "true"
- key: /org/gnome/desktop/interface/font-name
  value: "'Source Sans Pro 10'"
- key: /org/gnome/desktop/interface/monospace-font-name
  value: "'Source Code Pro 12'"
- key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
  value: "true"
- key: /org/gnome/desktop/search-providers/disable-external
  value: "true"
- key: /org/gnome/desktop/session/idle-delay
  value: "uint32 0"
- key: /org/gnome/desktop/wm/preferences/titlebar-uses-system-font
  value: "true"
- key: /org/gnome/gedit/preferences/editor/display-line-numbers
  value: "true"
- key: /org/gnome/gedit/preferences/editor/insert-spaces
  value: "true"
- key: /org/gnome/gedit/preferences/editor/scheme
  value: "'oblivion'"
- key: /org/gnome/gedit/preferences/editor/tabs-size
  value: "uint32 4"
- key: /org/gnome/gedit/preferences/editor/use-default-font
  value: "true"
- key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
  value: "true"
- key: /org/gnome/settings-daemon/plugins/media-keys/screensaver
  value: "'<Super>l'"
- key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
  value: "'nothing'"
- key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
  value: "'suspend'"
- key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout
  value: "'1800'"
- key: /org/gnome/settings-daemon/plugins/xsettings/overrides
  value: "{'Gtk/ShellShowsAppMenu': <0>}"
- key: /org/gnome/shell/enable-hot-corners
  value: "false"
- key: /org/gnome/shell/enabled-extensions
  value: "['launch-new-instance@gnome-shell-extensions.gcampax.github.com']"
- key: /org/gnome/shell/favorite-apps
  value: "['org.gnome.Nautilus.desktop',
           'org.gnome.gedit.desktop',
           'firefox.desktop']"
- key: /org/gnome/shell/overrides/dynamic-workspaces
  value: "true"
- key: /org/gnome/shell/overrides/workspaces-only-on-primary
  value: "false"
- key: /org/gnome/Terminal/Legacy/Settings/new-terminal-mode
  value: "'tab'"

firefox_preferences:
#    - comment: 'Non-menu -> Fix dark theme issue'
#      key: 'widget.content.gtk-theme-override'
#      value: 'Adwaita'
- comment: 'Misc -> Reject settings import from another browser'
  key: 'browser.newtabpage.activity-stream.migrationExpired'
  value: 'true'
- comment: 'Customize... -> Title Bar -> Uncheck'
  key: 'browser.tabs.drawInTitlebar'
  value: 'true'
- comment: 'Customize... -> Themes -> Dark'
  key: 'lightweightThemes.selectedThemeID'
  value: '"firefox-compact-dark@mozilla.org"'
- comment: 'Preferences -> General -> Tabs -> Warn you when closing multiple tabs -> Uncheck'
  key: 'browser.tabs.warnOnClose'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Web Search'
  key: 'browser.newtabpage.activity-stream.showSearch'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Top Sites'
  key: 'browser.newtabpage.activity-stream.feeds.topsites'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Highlights'
  key: 'browser.newtabpage.activity-stream.feeds.section.highlights'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Visited Pages'
  key: 'browser.newtabpage.activity-stream.section.highlights.includeVisited'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Bookmarks'
  key: 'browser.newtabpage.activity-stream.section.highlights.includeBookmarks'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Most Recent Download'
  key: 'browser.newtabpage.activity-stream.section.highlights.includeDownloads'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Pages Saved to Pocket'
  key: 'browser.newtabpage.activity-stream.section.highlights.includePocket'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Snippets'
  key: 'browser.newtabpage.activity-stream.feeds.snippets'
  value: 'false'
- comment: 'Preferences -> Home -> Firefox Home Content -> Top Sites -> Remove all defaults'
  key: 'browser.newtabpage.activity-stream.default.sites'
  value: '""'
- comment: 'Preferences -> Home -> Firefox Home Content -> Top Sites -> Remove all pinned'
  key: 'browser.newtabpage.pinned'
  value: '"[]"'
- comment: 'Preferences -> Search -> One-Click Search Engines -> Hide unused search engines'
  key: 'browser.search.hiddenOneOffs'
  value: '"Bing,Amazon.co.uk,Chambers (UK),DuckDuckGo,eBay,Twitter,Wikipedia (en)"'
- comment: 'Preferences -> Privacy & Security -> Logins & Passwords -> Ask to save logins and passwords for web sites'
  key: 'signon.rememberSignons'
  value: 'false'
- comment: 'Preferences -> Privacy & Security -> Permissions -> Location -> Block new requests asking to access your location'
  key: 'permissions.default.geo'
  value: '2'
- comment: 'Preferences -> Privacy & Security -> Permissions -> Camera -> Block new requests asking to access your camera'
  key: 'permissions.default.camera'
  value: '2'
- comment: 'Preferences -> Privacy & Security -> Permissions -> Microphone -> Block new requests asking to access your microphone'
  key: 'permissions.default.microphone'
  value: '2'
- comment: 'Preferences -> Privacy & Security -> Permissions -> Notifications -> Block new requests asking to allow notifications'
  key: 'permissions.default.desktop-notification'
  value: '2'
#    - comment: 'Preferences -> Privacy & Security -> Permissions -> Block web sites from automatically playing sound'
#      key: 'media.autoplay.default'
#      value: '1'
- comment: 'Preferences -> Privacy & Security -> Firefox Data Collection and Use -> Allow Firefox to send technical and interaction data to Mozilla'
  key: 'datareporting.healthreport.uploadEnabled'
  value: 'false'
- comment: 'Preferences -> Privacy & Security -> Firefox Data Collection and Use -> Allow Firefox to install and run studies'
  key: 'app.shield.optoutstudies.enabled'
  value: 'false'
- comment: 'Preferences -> Privacy & Security -> Firefox Data Collection and Use -> Allow Firefox to make personalised extension recommendations'
  key: 'browser.discovery.enabled'
  value: 'false'
- comment: 'Preferences -> Privacy & Security -> Firefox Data Collection and Use -> Allow Firefox to send backlogged crash reports on your behalf'
  key: 'browser.crashReports.unsubmittedCheck.autoSubmit2'
  value: 'false'
