---

- name: 'Check if there is an existing `~/.bash_aliases`'
  stat:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
  register: bash_aliases
  changed_when: false

- name: 'Backup existing `~/.bash_aliases` (if it exists)'
  when: bash_aliases.stat.exists
  copy:
    remote_src: yes
    src: "{{ ansible_env.HOME }}/.bash_aliases"
    dest: "{{ backup_dir }}/.bash_aliases"
  changed_when: false

- name: 'Envvars'
  lineinfile:
    create: yes
    line: "{{ item }}"
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  with_items:
  - export HISTTIMEFORMAT='%FT%T%z  '
  - export TZ='Europe/London'

- name: 'Alias: Update and reboot if necessary'
  lineinfile:
    create: yes
    line: alias updates='sudo apt update; sudo unattended-upgrade -v; sudo test -f /run/reboot-required && sudo systemctl reboot'
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
