---

- name: 'Assess initial SSH connection (if exists)'
  shell: echo {{ ansible_env['SSH_CONNECTION'] }} | awk '{print $NF}'
  register: initial_ssh_connection
  changed_when: false
  when: ansible_env['SSH_CONNECTION'] is defined

- name: 'UFW allow for existing connection (if exists)'
  become: true
  ufw:
    rule: allow
    port: "{{ initial_ssh_connection.stdout }}"
    proto: tcp
  when: initial_ssh_connection.stdout is defined

- name: 'UFW deny incoming'
  become: true
  ufw:
    policy: deny
    direction: incoming

- name: 'UFW allow outgoing'
  become: true
  ufw:
    policy: allow
    direction: outgoing

- name: 'UFW enable'
  become: true
  ufw:
    state: enabled

- name: 'UFW service started, enabled'
  become: true
  systemd:
    name: ufw.service
    masked: no
    state: started
    enabled: yes
