---

# Repositories
- name: 'Respositories'
  include_tasks: repositories.yml
  tags:
  - repositories

# Patching
- name: 'Patching'
  include_tasks: patching.yml
  tags:
  - patching

# Apply Upgrades
- name: 'Upgrades'
  include_tasks: upgrades.yml
  tags:
  - upgrades

# login.defs
- name: 'login.defs'
  include_tasks: login_defs.yml
  tags:
  - login_defs

# Packages
- name: 'Packages'
  include_tasks: packages.yml
  tags:
  - packages

# Firewall
- name: 'Firewall'
  include_tasks: firewall.yml
  tags:
  - firewall

# MOTD
- name: 'MOTD'
  include_tasks: motd.yml
  tags:
  - motd

# NTP
- name: 'NTP'
  include_tasks: ntp.yml
  tags:
  - ntp

# Privacy
- name: 'Privacy'
  include_tasks: privacy.yml
  tags:
  - privacy

# Bash
- name: 'BASH'
  include_tasks: bash.yml
  tags:
  - bash

# GRUB
- name: 'GRUB'
  include_tasks: grub.yml
  when: "'raspi' not in ansible_kernel"
  tags:
  - grub

# Raspberry Pi
- name: 'Raspberry Pi'
  include_tasks: pi.yml
  when: "'raspi' in ansible_kernel"
  tags:
  - pi3

# Data Mount
- name: 'Data Mount'
  include_tasks: data_mount.yml
  tags:
  - data_mount
