---

- name: 'Backup existing /etc/apt/sources.list.d/ubuntu.sources'
  become: true
  copy:
    remote_src: yes
    src: /etc/apt/sources.list.d/ubuntu.sources
    dest: "{{ backup_dir }}/ubuntu.sources"
  changed_when: false

- name: 'Deploy new /etc/apt/sources.list.d/ubuntu.sources (excluding multiverse)'
  become: true
  template:
    src: ubuntu.sources_exclude_multiverse.j2
    dest: /etc/apt/sources.list.d/ubuntu.sources
  when: (not enable_multiverse) and
        ('raspi' not in ansible_kernel)

- name: 'Deploy new /etc/apt/sources.list.d/ubuntu.sources (including multiverse)'
  become: true
  template:
    src: ubuntu.sources_include_multiverse.j2
    dest: /etc/apt/sources.list.d/ubuntu.sources
  when: (enable_multiverse) or
        ('raspi' in ansible_kernel)  # multiverse required for `linux-firmware-raspi2`

- name: 'Update APT cache'
  become: true
  apt:
    force_apt_get: yes
    update_cache: yes
  changed_when: false
