---

- name: 'Ensure snapd.service, snapd.socket are unmasked'
  become: true
  systemd:
    name: "{{ item }}"
    masked: no
  changed_when: false
  loop:
  - snapd.service
  - snapd.socket

- name: 'Ensure snapd.service, snapd.socket are running'
  become: true
  systemd:
    name: "{{ item }}"
    state: started
  changed_when: false
  loop:
  - snapd.service
  - snapd.socket

- name: 'list non-snapd, non-base snaps'
  become: true
  shell: snap list | awk '$1 !~ /^\s*Name/ && $6 !~ /(base|snapd)/ {print $1}'
  register: snap_list_non_base
  changed_when: false

- name: 'Uninstall non-snapd, non-base snaps'
  become: true
  shell: snap remove {{ item }}
  loop: "{{ snap_list_non_base.stdout_lines }}"

- name: 'list non-snapd, base snaps'
  become: true
  shell: snap list | awk '$1 !~ /^\s*Name/ && $6 ~ /base/ {print $1}'
  register: snap_list_base
  changed_when: false

- name: 'Uninstall non-snapd, base snaps'
  become: true
  shell: snap remove {{ item }}
  loop: "{{ snap_list_base.stdout_lines }}"

#- name: 'Stop, disable, mask: snapd.service, snapd.socket'
#  become: true
#  systemd:
#    name: "{{ item }}"
#    state: stopped
#    enabled: no
#    masked: yes
#  changed_when: false
#  loop:
#  - snapd.service
#  - snapd.socket
