---

- name: '`python3-psutil` dependency for `dconf` module'
  become: true
  apt:
    name: python3-psutil
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: 'Read Ptyxis default profile UUID'
  dconf:
    key: "/org/gnome/Ptyxis/default-profile-uuid"
    state: read
  register: ptyxis_default_profile_uuid
  changed_when: false

- name: 'dconf settings'
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ query('items', dconf_options)}}"
