---

- name: 'Ensure ~/.fonts/ directory exists'
  file:
    path: "{{ ansible_env.HOME }}/.fonts/"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0775

- name: 'Ensure fonts directories exist'
  file:
    path: "{{ ansible_env.HOME }}/.fonts/{{ item.dest }}/"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0775
  loop: "{{ query('items', google_fonts)}}"

- name: 'Fonts present'
  unarchive:
    src: 'https://fonts.google.com/download?family={{ item.src }}'
    dest: "{{ ansible_env.HOME }}/.fonts/{{ item.dest }}/"
    remote_src: yes
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0775
  loop: "{{ query('items', google_fonts)}}"
  register: font_unarchive

- name: 'Rebuild font cache'
  when: font_unarchive.changed
  command: fc-cache -f -v {{ ansible_env.HOME }}/.fonts/
