---

# Ubuntu 24.04 conflicts when installing gnome if pulseaudio not present
- name: 'Install pulseaudio'
  become: true
  apt:
    name: pulseaudio
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: 'Install desktop packages'
  become: true
  apt:
    name: "{{ apt_packages_desktop }}"
    force_apt_get: yes
    update_cache: yes
    state: latest
