---

- name: '`docker-ce` and `docker-compose-plugin` packages (latest)'
  become: true
  apt:
    name:
    - docker-ce
    - docker-compose-plugin
    force_apt_get: yes
    update_cache: yes
    state: latest
  when: docker_version is undefined

- name: '`docker-ce` and `docker-compose-plugin` packages (specific version)'
  become: true
  apt:
    name:
    - docker-ce={{ docker_version }}
    - docker-compose-plugin
    force_apt_get: yes
    update_cache: yes
    state: present
  when: docker_version is defined

- name: 'Add user to `docker` group'
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  register: docker_user_group

- name: 'Note if logout will be required'
  when: docker_user_group.changed
  set_fact:
    logout_required: true

- name: 'Prevent upgrades to docker-ce'
  become: true
  command: apt-mark hold docker-ce
  register: apt_hold_docker
  changed_when: "'docker-ce was already set on hold' not in apt_hold_docker.stdout"
  when: docker_version_hold
