---

# Repository
- name: 'Ensure the keyrings directory exists'
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: 0755

- name: 'Download Docker''s Linux signing key'
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker-linux.asc
    mode: 0644

- name: 'Check for existing Docker repository file'
  stat:
    path: /etc/apt/sources.list.d/docker.sources
  register: docker_file

- name: 'Backup existing any existing Docker repository file'
  become: true
  copy:
    remote_src: yes
    src: /etc/apt/sources.list.d/docker.sources
    dest: "{{ backup_dir }}/docker.sources"
  when: docker_file.stat.exists
  changed_when: false

- name: 'Docker repository'
  become: true
  template:
    src: docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.sources
    mode: 0644

- name: "Apt update cache"
  become: true
  apt:
    update_cache: true
  changed_when: false

# sudo apt-cache policy -> o:a pairs (e.g. Docker:jammy)
- name: 'Allow Unattended-upgrade to use Docker Repo'
  become: true
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?"Docker:${distro_codename}";\s*$'
    line: '        "Docker:${distro_codename}";'
    insertafter: '^\s*(//\s*)?"\${distro_id}:\${distro_codename}-backports";$'

# Docker-CE
- name: 'Docker'
  include_tasks: docker.yml
  when: runtime == "docker"

# containerd
- name: 'Containerd'
  include_tasks: containerd.yml
  when: runtime == "containerd"
