---

- name: 'Include Kubernetes common tasks'
  include: kubernetes_common.yml

- name: 'Include Kubernetes Master tasks'
  include: kubernetes_master.yml
  when: kubernetes_role == 'master'

- name: 'Include Kubernetes common tasks'
  include: kubernetes_node.yml
  when: kubernetes_role == 'node'
