---

- name: 'Include Kubernetes common tasks'
  ansible.builtin.include_tasks: kubernetes_common.yml

- name: 'Include Kubernetes Master tasks'
  ansible.builtin.include_tasks: kubernetes_master.yml
  when: kubernetes_role == 'master'

- name: 'Include Kubernetes common tasks'
  ansible.builtin.include_tasks: kubernetes_node.yml
  when: kubernetes_role == 'node'
