---

apt_packages_workstation:
# Utilities
- curl                           # main
- sysstat                        # main
- git                            # main
- pwgen                          # universe
- jq                             # universe
# Programming
- python-pip                     # universe
- python3-pip                    # universe
# Virtualization
- libvirt-bin                    # main
- qemu-kvm                       # main
- virt-manager                   # universe
- virt-viewer                    # universe
- vagrant                        # universe
- vagrant-libvirt                # universe
