---

system:
  disk:
    uuid: asdf
  network:
    cidr_network_prefix_bits: 24

virtualization_type: libvirt

apt_packages_workstation:
# Utilities
- curl                           # main
- sysstat                        # main
- git                            # main
- pwgen                          # universe
- jq                             # universe
# Virtualization
- virt-manager                   # universe
- virt-viewer                    # universe
- vagrant                        # universe

apt_packages_libvirt:
- qemu-kvm                       # main
- libvirt-daemon                 # main
- vagrant-libvirt                # universe

apt_packages_virtualbox:
- virtualbox                     # multiverse

vscode:
  extensions:
  - googlecloudtools.cloudcode
