---
device_mapper:
  - vg: media
    lv: image
  - vg: media
    lv: music
  - vg: media
    lv: games
  - vg: media
    lv: video

apt_packages_media:
  - libcec7 # universe
  - cec-utils # universe
  - input-remapper # universe
  - wayland-utils # universe (required for wayland-info in es-de.service)

